title: Nicolas Stahl
iconURL: assets/images_icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug



plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
